### ISSUE TITLE
Documentación de como realiazar un buen informe de TFG

### ISSUE THREAD

**Issue by jppasvit** [jppasvit/geo-indoor#2]
Buscaremos aclarar nuestras ideas a la hora de saber como redactar bien el informe del TFG y que pasos seguir para conseguirlo

**Comment by clopezno** [comment]
En las secciones de la [plantilla de documentación](https://github.com/ubutfgm/plantillaLatex) se describe  el contenido del TFG. Falta adecuarlo con tu TFG. 
Puedes tomar como ejemplo este [TFG](http://digit-moodle.blogspot.com.es/2017/02/un-tfg-en-ingenieria-informatica-de-10.html)

**Comment by jppasvit** [comment]
Entendido

**Comment by jppasvit** [comment]
https://drive.google.com/open?id=0B7FXDSE5FqwjcWtXVFpwZ0dwazA

He enfocado la introducción de otra manera, no se que te parecerá.

**Comment by clopezno** [comment]
El enfoque que se da es desde el punto de usuario . Quizás es mejor un enfoque desde el punto de vista de  una institución/empresa  que quiere dar un mejor servicio de información y de acceso a sus recursos ubicados  dentro de una construcción o edificio a los distintos usuarios de este.

**Comment by jppasvit** [comment]
https://drive.google.com/open?id=0B7FXDSE5FqwjSGg2c3N3SHAzZE0

**Comment by jppasvit** [comment]
https://drive.google.com/open?id=0B7FXDSE5FqwjSGg2c3N3SHAzZE0
