### ISSUE TITLE
Obtención de los planos del museo de la evolución

### ISSUE THREAD

**Issue by jppasvit** [jppasvit/geo-indoor#3]
Se tiene pensado utilizar los planos del museo de la evolución de Burgos

**Comment by clopezno** [comment]
Vale cualquier otro edificio público cuyos planos estén disponibles: Hospitales, Bibliotecas, Universidades...

**Comment by jppasvit** [comment]
Los planos ya se han conseguido, estoy a la espera de que el archivo municipal me mande la copia digital.

**Comment by jppasvit** [comment]
https://drive.google.com/open?id=0B7FXDSE5FqwjeGRnS0FBSTh1cEU
