### ISSUE TITLE
Aclaración de dudas sobre que hacer en el primer Sprint

### ISSUE THREAD

**Issue by jppasvit** [jppasvit/geo-indoor#5]
Se debe saber cuales son los objetivos del primer Sprint

**Comment by clopezno** [comment]
@jppasvit ya tienes disponible la descripción y asignación del TFG. Lo puedes ver en este [enlace](https://clopezno.github.io/ActualesSist.html).

En agilidad para la documentación del sprint no se da un informe se miran las issues. Si una issue es de documentación se asocia el commit de documentación necesario (en Latex), enlace al documento en GDrive  o se adjunta el subdocumento en la issue.

Sobre tu duda de conceptos teóricos cito literalemente lo que sugiere en la [plantilla de documentación](https://github.com/ubutfgm/plantillaLatex)
 
_"En aquellos proyectos que necesiten para su comprensión y desarrollo de unos conceptos teóricos de una determinada materia o de un determinado dominio de conocimiento, debe existir un apartado que sintetice dichos conceptos."_

En este proyecto particular creo que el dominio de conocimiento  sugiere tratar los conceptos teóricos de geolocalización, formatos gráficos escalables, lenguajes de etiquetas... si incluyes procesamiento de voz para las búsquedas.

**Comment by jppasvit** [comment]
Entendido
