### ISSUE TITLE
Conceptos Teóricos

### ISSUE THREAD

**Issue by jppasvit** [jppasvit/geo-indoor#7]

**Comment by clopezno** [comment]
Añade  en la descripción una enumeración con los conceptos teóricos. Ayuda a clarificar la tarea.

**Comment by jppasvit** [comment]
- Geolocalización 
- Formatos gráficos escalables
- Lenguajes de etiquetas 
- Procesamiento de voz

**Comment by jppasvit** [comment]
https://drive.google.com/drive/folders/0B7FXDSE5FqwjSXpsbkFMdUx1SHM?usp=sharing
