### ISSUE TITLE
Supervisión del proyecto

### ISSUE THREAD

**Issue by jppasvit** [jppasvit/geo-indoor#8]
Me preguntaba si podríamos quedar el jueves 11/05/2017 para solucionar algunas cuestiones y ver como voy

**Comment by clopezno** [comment]
Nos vemos a las 19:30 en mi despacho EPSA1. 
Intenta añadir issues o commits para que pueda conocer tu trabajo.

Saludos
Carlos López

**Comment by jppasvit** [comment]
Carlos, no he tenido tiempo para avanzar el proyecto, y quedar para no mostrarte nada sería una perdida de tiempo, asi que por mi anularía la cita del jueves a las 19:30, pero como veas

**Comment by clopezno** [comment]
De acuerdo. Anulamos la revisión.
